---
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2023 Maxwell G <maxwell@gtmx.me

name: nox
'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Thursday at 04:15 UTC)
  schedule:
    - cron: '15 4 * * 4'
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

jobs:
  nox:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible-build-data
    strategy:
      fail-fast: false
      matrix:
        include:
          - session: lint
            python-versions: "3.13"
    name: "Run nox ${{ matrix.session }} session"
    steps:
      - name: Check out ansible-build-data
        uses: actions/checkout@v5
        with:
          path: ansible-build-data
      - name: Setup nox
        uses: wntrblm/nox@2025.05.01
        with:
          python-versions: "${{ matrix.python-versions }}"
      - name: Set up nox environments
        run: |
          nox -v -e "${{ matrix.session }}" --install-only
      - name: "Run nox -e ${{ matrix.session }}"
        run: |
          nox -v -e "${{ matrix.session }}" --reuse-existing-virtualenvs --no-install
